from reportlab.platypus import SimpleDocTemplate, Paragraph, Spacer
from reportlab.lib.styles import getSampleStyleSheet, ParagraphStyle
from reportlab.lib.pagesizes import A4
from reportlab.lib import colors
import uuid


def create_pdf(data, filename=None):
    if not filename:
        filename = f"{uuid.uuid4()}.pdf"

    doc = SimpleDocTemplate(
        filename,
        pagesize=A4,
        rightMargin=40,
        leftMargin=40,
        topMargin=40,
        bottomMargin=40
    )

    styles = getSampleStyleSheet()

    # =========================
    # 🎨 CUSTOM STYLES
    # =========================

    title_style = ParagraphStyle(
        name="Title",
        parent=styles["Heading1"],
        fontSize=24,
        spaceAfter=20,
        textColor=colors.HexColor("#1e3a8a"),  # blue
        alignment=1  # center
    )

    heading_style = ParagraphStyle(
        name="Heading",
        parent=styles["Heading2"],
        fontSize=16,
        spaceBefore=12,
        spaceAfter=8,
        textColor=colors.HexColor("#0f172a"),
    )

    bullet_style = ParagraphStyle(
        name="Bullet",
        parent=styles["Normal"],
        fontSize=12,
        leftIndent=12,
        spaceAfter=6,
        textColor=colors.HexColor("#334155")
    )

    elements = []

    # =========================
    # 🟦 TITLE
    # =========================
    elements.append(Paragraph(f"<b>{data['title']}</b>", title_style))
    elements.append(Spacer(1, 15))

    # =========================
    # 📄 SECTIONS
    # =========================
    for i, section in enumerate(data["sections"], start=1):

        # Section heading
        elements.append(
            Paragraph(f"{i}. <b>{section['heading']}</b>", heading_style)
        )

        elements.append(Spacer(1, 6))

        # Bullet points
        for point in section["points"]:
            elements.append(
                Paragraph(f"• {point}", bullet_style)
            )

        # Space between sections
        elements.append(Spacer(1, 15))

    # =========================
    # 📌 FOOTER
    # =========================
    elements.append(Spacer(1, 20))
    elements.append(
        Paragraph(
            "<i>Generated by AI Assistant</i>",
            styles["Normal"]
        )
    )

    doc.build(elements)
    return filename