from pptx import Presentation
from pptx.util import Pt, Inches
from pptx.dml.color import RGBColor
from pptx.enum.text import PP_ALIGN
from app.image_service import fetch_image
import os
import uuid

def create_ppt(data, filename=None):
    if not filename:
        filename = f"{uuid.uuid4()}.pptx"

    prs = Presentation()

    # =========================
    # 🎯 TITLE SLIDE
    # =========================
    slide_layout = prs.slide_layouts[6]  # blank layout
    slide = prs.slides.add_slide(slide_layout)

    # Background
    bg = slide.background
    fill = bg.fill
    fill.solid()
    fill.fore_color.rgb = RGBColor(15, 23, 42)  # dark navy

    # Title
    title_box = slide.shapes.add_textbox(Inches(1), Inches(2), Inches(8), Inches(2))
    title_tf = title_box.text_frame
    title = title_tf.text = data["title"]

    title_tf.paragraphs[0].font.size = Pt(42)
    title_tf.paragraphs[0].font.bold = True
    title_tf.paragraphs[0].font.color.rgb = RGBColor(255, 255, 255)
    title_tf.paragraphs[0].alignment = PP_ALIGN.CENTER

    # Subtitle
    sub_box = slide.shapes.add_textbox(Inches(1), Inches(4), Inches(8), Inches(1))
    sub_tf = sub_box.text_frame
    sub_tf.text = "Generated by AI"

    sub_tf.paragraphs[0].font.size = Pt(18)
    sub_tf.paragraphs[0].font.color.rgb = RGBColor(148, 163, 184)
    sub_tf.paragraphs[0].alignment = PP_ALIGN.CENTER

    # =========================
    # 📊 CONTENT SLIDES
    # =========================
    for slide_data in data["slides"]:
        slide_layout = prs.slide_layouts[6]
        slide = prs.slides.add_slide(slide_layout)

        # Background
        bg = slide.background
        fill = bg.fill
        fill.solid()
        fill.fore_color.rgb = RGBColor(30, 41, 59)
        #images 
        query = slide_data["heading"]

        image_path = fetch_image(query)

        if image_path and os.path.exists(image_path):
            slide.shapes.add_picture(
                image_path,
                Inches(6),
                Inches(2),
                width=Inches(3)
            )
        if image_path and os.path.exists(image_path):
            os.remove(image_path)
        # Accent line
        accent = slide.shapes.add_shape(
            1, Inches(0.5), Inches(1), Inches(0.2), Inches(5)
        )
        accent.fill.solid()
        accent.fill.fore_color.rgb = RGBColor(99, 102, 241)  # indigo

        # Title
        title_box = slide.shapes.add_textbox(Inches(1), Inches(0.8), Inches(8), Inches(1))
        tf = title_box.text_frame
        tf.text = slide_data["heading"]

        tf.paragraphs[0].font.size = Pt(32)
        tf.paragraphs[0].font.bold = True
        tf.paragraphs[0].font.color.rgb = RGBColor(255, 255, 255)

        # Bullet points
        content_box = slide.shapes.add_textbox(Inches(1), Inches(2), Inches(8), Inches(4))
        tf = content_box.text_frame

        for point in slide_data["points"]:
            p = tf.add_paragraph()
            p.text = point
            p.level = 0
            p.font.size = Pt(20)
            p.font.color.rgb = RGBColor(203, 213, 225)

    prs.save(filename)
    return filename