from pptx import Presentation
from pptx.util import Pt, Inches
from pptx.dml.color import RGBColor
from pptx.enum.text import PP_ALIGN
from app.image_service import fetch_image
import os
import uuid

def create_ppt(data, filename=None):
    if not filename:
        filename = f"{uuid.uuid4()}.pptx"

    prs = Presentation()

    # =========================
    # 🎯 TITLE SLIDE
    # =========================
    slide = prs.slides.add_slide(prs.slide_layouts[6])

    # Background
    bg = slide.background
    fill = bg.fill
    fill.solid()
    fill.fore_color.rgb = RGBColor(15, 23, 42)

    # Title
    title_box = slide.shapes.add_textbox(Inches(1), Inches(2.5), Inches(8), Inches(2))
    tf = title_box.text_frame
    tf.text = data["title"]

    tf.paragraphs[0].font.size = Pt(44)
    tf.paragraphs[0].font.bold = True
    tf.paragraphs[0].font.color.rgb = RGBColor(255, 255, 255)
    tf.paragraphs[0].alignment = PP_ALIGN.CENTER

    # Subtitle
    sub_box = slide.shapes.add_textbox(Inches(1), Inches(4.5), Inches(8), Inches(1))
    tf = sub_box.text_frame
    tf.text = "Generated by AI"

    tf.paragraphs[0].font.size = Pt(18)
    tf.paragraphs[0].font.color.rgb = RGBColor(148, 163, 184)
    tf.paragraphs[0].alignment = PP_ALIGN.CENTER

    # =========================
    # 📊 CONTENT SLIDES
    # =========================
    for index, slide_data in enumerate(data["slides"]):
        slide = prs.slides.add_slide(prs.slide_layouts[6])

        # Background
        bg = slide.background
        fill = bg.fill
        fill.solid()
        fill.fore_color.rgb = RGBColor(30, 41, 59)

        # 🔥 Better image query
        query = f"{data['title']} {slide_data['heading']}"
        image_path = fetch_image(query)

        # =========================
        # 🖼 IMAGE (RIGHT SIDE)
        # =========================
        if image_path and os.path.exists(image_path):
            slide.shapes.add_picture(
                image_path,
                Inches(6.5),
                Inches(2),
                width=Inches(3)
            )
            os.remove(image_path)

        # =========================
        # 🎨 ACCENT LINE
        # =========================
        accent = slide.shapes.add_shape(
            1, Inches(0.5), Inches(1), Inches(0.2), Inches(5)
        )
        accent.fill.solid()
        accent.fill.fore_color.rgb = RGBColor(99, 102, 241)

        # =========================
        # 🏷 TITLE
        # =========================
        title_box = slide.shapes.add_textbox(Inches(1), Inches(0.8), Inches(6), Inches(1))
        tf = title_box.text_frame
        tf.text = slide_data["heading"]

        tf.paragraphs[0].font.size = Pt(34)
        tf.paragraphs[0].font.bold = True
        tf.paragraphs[0].font.color.rgb = RGBColor(255, 255, 255)

        # =========================
        # 📌 BULLETS (LEFT SIDE)
        # =========================
        content_box = slide.shapes.add_textbox(Inches(1), Inches(2), Inches(5), Inches(4))
        tf = content_box.text_frame

        for point in slide_data["points"]:
            p = tf.add_paragraph()
            p.text = f"• {point}"
            p.level = 0
            p.font.size = Pt(22)
            p.font.color.rgb = RGBColor(203, 213, 225)

        # =========================
        # 🔢 SLIDE NUMBER
        # =========================
        num_box = slide.shapes.add_textbox(Inches(9), Inches(0.3), Inches(1), Inches(1))
        tf = num_box.text_frame
        tf.text = str(index + 1)

        tf.paragraphs[0].font.size = Pt(14)
        tf.paragraphs[0].font.color.rgb = RGBColor(148, 163, 184)
        tf.paragraphs[0].alignment = PP_ALIGN.RIGHT

    prs.save(filename)
    return filename